const Auth = {
  html: `<div class="card card-pad" style="max-width:400px;margin:20px auto;text-align:center;">
  <h3>Login / Signup</h3><input id="email" placeholder="Email"><input id="password" type="password" placeholder="Password"><input id="username" placeholder="Username (signup ku)">
  <div style="display:flex;gap:8px;margin-top:8px;"><button onclick="Auth.signup()" class="btn-yellow">SIGNUP 🔥</button><button onclick="Auth.login()" class="btn-white" style="flex:1;">LOGIN 🔑</button></div><p id="authMsg" style="color:#ffeb3b;margin-top:8px;"></p></div>`,

  init(){ document.getElementById("authPage").innerHTML=this.html; this.check(); },
  async check(){ let {data}=await sb.auth.getSession(); if(data.session){ currentUser=data.session.user; await this.loadProfile(); document.getElementById("authPage").style.display='none'; document.getElementById("mainApp").style.display='block'; App.show('home'); } },
  async signup(){ const e=document.getElementById("email").value.trim(), p=document.getElementById("password").value.trim(), u=document.getElementById("username").value.trim().toLowerCase(); if(!e||!p||!u) return alert("Ellam venum da!"); let {data:ex}=await sb.from('profiles').select('username').eq('username',u).single(); if(ex) return document.getElementById("authMsg").innerText="Username irukku da!"; let {data,error}=await sb.auth.signUp({email:e,password:p}); if(error) return document.getElementById("authMsg").innerText=error.message; if(data.user){ await sb.from('profiles').insert([{id:data.user.id,username:u}]); document.getElementById("authMsg").innerText="Success da! Login pannu!"; } },
  async login(){ let e=document.getElementById("email").value.trim(), p=document.getElementById("password").value.trim(); let {data,error}=await sb.auth.signInWithPassword({email:e,password:p}); if(error) return document.getElementById("authMsg").innerText=error.message; currentUser=data.user; await this.loadProfile(); document.getElementById("authPage").style.display='none'; document.getElementById("mainApp").style.display='block'; App.show('home'); },
  async loadProfile(){ let {data}=await sb.from('profiles').select('*').eq('id',currentUser.id).single(); currentProfile=data; if(!data){ let uname=currentUser.email.split('@')[0]+Math.floor(Math.random()*100); await sb.from('profiles').insert([{id:currentUser.id,username:uname}]); let {data:d2}=await sb.from('profiles').select('*').eq('id',currentUser.id).single(); currentProfile=d2; } },
  logout(){ sb.auth.signOut(); location.reload(); }
}
